spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: bekberov
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  jwt:
      header: Authorization
      secret: proselyte
      expiration: 604800
server:
  port: 8080
  error:
    include-message: always
    include-exception: true

application:
  name: my-rest-api
user:
  age:
    limit: 18

